port_start: 8000
hf_home: /tmp/hf_home
hf_token: <TOKEN>
walltime: "4:00:00"
account: ModCon
queue: prod
filesystems: flare:home
conda_env: /home/ogokdemir/Aegis/assets/condapacks/vllm_oss_conda_pack_01082026.tar.gz
aegis_env: /home/ogokdemir/.conda/envs/exaforge-env/


models:
  - model: openai/gpt-oss-120b
    #PBS will request 64 / (12 / tensor_parallel_size) nodes on Aurora. Ensure divisibility.
    instances: 768
    tensor_parallel_size: 4
    model_source: /flare/datasets/model-weights/hub/models--openai--gpt-oss-120b
    download_weights: false
    extra_vllm_args:
      - --max-model-len
      - "131072" # this should fit the full paper and the ~4k token paper card.

wait: true
bench: false
