port_start: 8000
hf_home: /tmp/hf_home
walltime: "01:00:00"
account: ModCon
queue: debug
filesystems: flare:home
endpoints_file: /home/ogokdemir/ExaForge/hostfiles/endpoints.txt
conda_env: /home/ogokdemir/Aegis/assets/condapacks/vllm_oss_conda_pack_01082026.tar.gz
aegis_env: /home/ogokdemir/.conda/envs/exaforge-env/


models:
  - model: openai/gpt-oss-20b
    instances: 2
    tensor_parallel_size: 4
    model_source: /flare/datasets/model-weights/hub/models--openai--gpt-oss-20b
    download_weights: true
    extra_vllm_args:
      - --max-model-len
      - "4096"

wait: true
bench: true
bench_num_prompts: 100